services:
  neo4j:
    image: 'neo4j:5'
    ports:
      - '7474'
      - '7687'
    environment:
      NEO4J_AUTH: 'neo4j/password'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
